apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-app
  template:
    metadata:
      labels:
        app: mlops-app
    spec:
      containers:
      - name: mlops-container
        image: princebaja07/mlops-flask-app:v1
        ports:
        - containerPort: 5000
